package com.pathforge.utility;

public class Data {
    public static String getMessage(String otp,String name) {
        String htmlContent = ""
                + "<!DOCTYPE html>\n"
                + "<html>\n"
                + "<head>\n"
                + "  <meta charset='UTF-8'>\n"
                + "  <title>Your OTP Code</title>\n"
                + "  <style>\n"
                + "    body {\n"
                + "      font-family: Arial, sans-serif;\n"
                + "      background-color: #f4f4f4;\n"
                + "      padding: 20px;\n"
                + "      margin: 0;\n"
                + "    }\n"
                + "    .container {\n"
                + "      max-width: 600px;\n"
                + "      margin: auto;\n"
                + "      background-color: #ffffff;\n"
                + "      border-radius: 8px;\n"
                + "      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\n"
                + "    }\n"
                + "    .header {\n"
                + "      padding: 20px;\n"
                + "      text-align: center;\n"
                + "      background-color: #007bff;\n"
                + "      color: white;\n"
                + "      border-top-left-radius: 8px;\n"
                + "      border-top-right-radius: 8px;\n"
                + "    }\n"
                + "    .content {\n"
                + "      padding: 30px;\n"
                + "    }\n"
                + "    .otp {\n"
                + "      margin: 30px 0;\n"
                + "      text-align: center;\n"
                + "      font-size: 28px;\n"
                + "      letter-spacing: 4px;\n"
                + "      font-weight: bold;\n"
                + "      color: #333;\n"
                + "    }\n"
                + "    .footer {\n"
                + "      padding: 15px;\n"
                + "      text-align: center;\n"
                + "      font-size: 12px;\n"
                + "      color: #888888;\n"
                + "      background-color: #f4f4f4;\n"
                + "      border-bottom-left-radius: 8px;\n"
                + "      border-bottom-right-radius: 8px;\n"
                + "    }\n"
                + "  </style>\n"
                + "</head>\n"
                + "<body>\n"
                + "  <table class='container' width='100%' cellpadding='0' cellspacing='0'>\n"
                + "    <tr>\n"
                + "      <td class='header'>\n"
                + "        <h2>Verification Code</h2>\n"
                + "      </td>\n"
                + "    </tr>\n"
                + "    <tr>\n"
                + "      <td class='content'>\n"
                + "        <p>Dear "+name+",</p>\n"
                + "        <p>We received a request to verify your email address. Please use the OTP below to complete your verification process:</p>\n"
                + "        <div class='otp'>" + otp + "</div>\n"
                + "        <p>This code is valid for the next <strong>10 minutes</strong>. Do not share it with anyone.</p>\n"
                + "        <p>If you did not request this, please ignore this email or contact support.</p>\n"
                + "        <p>Thank you,<br>Path Forge</p>\n"
                + "      </td>\n"
                + "    </tr>\n"
                + "    <tr>\n"
                + "      <td class='footer'>\n"
                + "        © 2025 Path Forge. All rights reserved.\n"
                + "      </td>\n"
                + "    </tr>\n"
                + "  </table>\n"
                + "</body>\n"
                + "</html>";
        return htmlContent;
    }

}
